require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/contributions", type: :request, inertia: true do
  # This should return the minimal set of attributes required to create a valid
  # Contribution. As you add validations to Contribution, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    let(:user) { create(:user) }
    subject { get user_contributions_url(user) }

    it_behaves_like "require_authentication"

    context "signed as another user" do
      let(:other_user) { create(:user) }

      before do
        sign_in_as(other_user)
      end

      it_behaves_like "only_for_current_user"
    end

    context "for current user" do
      before do
        sign_in_as(user)
      end

      it "renders a successful response" do
        # Contribution.create! valid_attributes
        subject
        expect(response).to be_successful
      end
    end
  end

  describe "GET /mes-contributions" do
    subject { get my_contributions_url }

    it_behaves_like "require_authentication"

    context "for current user" do
      before do
        sign_in_as(create(:user))
      end

      it "renders a successful response" do
        # Contribution.create! valid_attributes
        subject
        expect(response).to be_successful
      end
    end
  end

  describe "GET /mes-contributions/ajouter-une-association" do
    subject { get my_new_contributions_url }

    it_behaves_like "require_authentication"

    context "for current user" do
      before do
        sign_in_as(create(:user))
      end

      it "renders a successful response" do
        subject
        expect(response).to be_successful
      end
    end
  end

  xdescribe "GET /show" do
    it "renders a successful response" do
      contribution = Contribution.create! valid_attributes
      get contribution_url(contribution)
      expect(response).to be_successful
    end
  end

  xdescribe "GET /new" do
    it "renders a successful response" do
      get new_user_contribution_url
      expect(response).to be_successful
    end
  end

  xdescribe "GET /edit" do
    it "renders a successful response" do
      contribution = Contribution.create! valid_attributes
      get edit_contribution_url(contribution)
      expect(response).to be_successful
    end
  end

  xdescribe "POST /create" do
    context "with valid parameters" do
      it "creates a new Contribution" do
        expect {
          post contributions_url, params: {contribution: valid_attributes}
        }.to change(Contribution, :count).by(1)
      end

      it "redirects to the created contribution" do
        post contributions_url, params: {contribution: valid_attributes}
        expect(response).to redirect_to(contribution_url(Contribution.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Contribution" do
        expect {
          post contributions_url, params: {contribution: invalid_attributes}
        }.to change(Contribution, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post contributions_url, params: {contribution: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  xdescribe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested contribution" do
        contribution = Contribution.create! valid_attributes
        patch contribution_url(contribution), params: {contribution: new_attributes}
        contribution.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the contribution" do
        contribution = Contribution.create! valid_attributes
        patch contribution_url(contribution), params: {contribution: new_attributes}
        contribution.reload
        expect(response).to redirect_to(contribution_url(contribution))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        contribution = Contribution.create! valid_attributes
        patch contribution_url(contribution), params: {contribution: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  xdescribe "DELETE /destroy" do
    it "destroys the requested contribution" do
      contribution = Contribution.create! valid_attributes
      expect {
        delete contribution_url(contribution)
      }.to change(Contribution, :count).by(-1)
    end

    it "redirects to the contributions list" do
      contribution = Contribution.create! valid_attributes
      delete contribution_url(contribution)
      expect(response).to redirect_to(contributions_url)
    end
  end
end
