class ModifyTableNames < ActiveRecord::Migration[8.0]
  def up
    rename_table :causes, :osbl_causes if table_exists?(:causes)
    rename_table :locations, :osbl_locations if table_exists?(:locations)
    rename_table :intervention_areas, :osbl_intervention_areas if table_exists?(:intervention_areas)
    rename_table :keywords, :osbl_keywords if table_exists?(:keywords)
    rename_table :labels, :osbl_labels if table_exists?(:labels)
    rename_table :fund_sources, :osbl_fund_sources if table_exists?(:fund_sources)
    rename_table :annual_finances, :osbl_annual_finances if table_exists?(:annual_finances)
    rename_table :fund_allocations, :osbl_fund_allocations if table_exists?(:fund_allocations)
    rename_table :otps, :user_otps if table_exists?(:otps)
    rename_table :sessions, :user_sessions if table_exists?(:sessions)
    rename_table :osbl_creations, :contribution_osbl_creations if table_exists?(:osbl_creations)
    rename_table :osbl_updates, :contribution_osbl_updates if table_exists?(:osbl_updates)
    rename_table :feedbacks, :contribution_feedbacks if table_exists?(:feedbacks)
    rename_table :feature_requests, :contribution_feature_requests if table_exists?(:feature_requests)
    rename_table :bug_reports, :contribution_bug_reports if table_exists?(:bug_reports)
    rename_table :correction_requests, :contribution_correction_requests if table_exists?(:correction_requests)
    rename_table :others, :contribution_others if table_exists?(:others)
  end

  def down
    rename_table :osbl_causes, :causes if table_exists?(:osbl_causes)
    rename_table :osbl_locations, :locations if table_exists?(:osbl_locations)
    rename_table :osbl_intervention_areas, :intervention_areas if table_exists?(:osbl_intervention_areas)
    rename_table :osbl_keywords, :keywords if table_exists?(:osbl_keywords)
    rename_table :osbl_labels, :labels if table_exists?(:osbl_labels)
    rename_table :osbl_fund_sources, :fund_sources if table_exists?(:osbl_fund_sources)
    rename_table :osbl_annual_finances, :annual_finances if table_exists?(:osbl_annual_finances)
    rename_table :osbl_fund_allocations, :fund_allocations if table_exists?(:osbl_fund_allocations)
    rename_table :user_otps, :otps if table_exists?(:user_otps)
    rename_table :user_sessions, :sessions if table_exists?(:user_sessions)
    rename_table :contribution_osbl_creations, :osbl_creations if table_exists?(:contribution_osbl_creations)
    rename_table :contribution_osbl_updates, :osbl_updates if table_exists?(:contribution_osbl_updates)
    rename_table :contribution_feedbacks, :feedbacks if table_exists?(:contribution_feedbacks)
    rename_table :contribution_feature_requests, :feature_requests if table_exists?(:contribution_feature_requests)
    rename_table :contribution_bug_reports, :bug_reports if table_exists?(:contribution_bug_reports)
    rename_table :contribution_correction_requests, :correction_requests if table_exists?(:contribution_correction_requests)
    rename_table :contribution_others, :others if table_exists?(:contribution_others)
  end
end
