name: Deploy to Review

concurrency:
  group: review-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]


jobs:
  deploy:
    if: github.actor != 'github-actions[bot]' && github.actor != 'dependabot[bot]'
    environment:
      name: review
      url: ${{ env.REVIEW_APP_URL }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.216.0
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Expose GitHub Runtime for cache
        uses: crazy-max/ghaction-github-runtime@v3.0.0

      - name: Release Kamal lock
        run: bundle exec kamal lock release

      - name: Generate branch slug
        run: |
          ref=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          slug=$(echo "$ref" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-')
          slug=${slug%-}
          echo "SERVICE_NAME=$slug" >> $GITHUB_ENV
          echo "REVIEW_APP_URL=https://${slug}.review.benefactorum.org" >> $GITHUB_ENV

      - name: Deploy with Kamal
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          VERSION: ${{ github.sha }}
          SERVICE_NAME: ${{ env.SERVICE_NAME }}
        run: bundle exec kamal deploy -d review --version=$VERSION
