name: Deploy to Production
concurrency:
  group: production
  cancel-in-progress: true
on:
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: production
      url: https://benefactorum-production.benefactorum.org
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.214.0
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Expose GitHub Runtime for cache
        uses: crazy-max/ghaction-github-runtime@v3.0.0

      - name: Release Kamal lock
        run: bundle exec kamal lock release

      - name: Deploy with Kamal
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          VERSION: ${{ github.sha }}
        run: bundle exec kamal deploy --version=$VERSION
