name: Remove Old Docker Images
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # run every day at midnight, utc

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old test images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: benefactorum
          token: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          image-names: "staging production"
          cut-off: 1s
          keep-n-most-recent: 2
